"""Add featured column to Sequence table

Revision ID: 09ae21db0ff2
Revises: 5192c5f2f2c6
Create Date: 2025-06-03 20:33:02.509220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ae21db0ff2'
down_revision = '5192c5f2f2c6'
branch_labels = None
depends_on = None
from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sequence', schema=None) as batch_op:
        # Step 1: Add the column as nullable with a temporary default
        batch_op.add_column(sa.Column('featured', sa.Integer(), server_default='0', nullable=True))

    # Step 2: Update existing rows to ensure they have the default value (if not already set by server_default)
    # This step is technically optional if server_default works, but good for robustness.
    # SQLite's ADD COLUMN does set the default for new rows.
    # For existing rows, it defaults to NULL. We need to explicitly update them.
    op.execute("UPDATE sequence SET featured = 0 WHERE featured IS NULL")


    with op.batch_alter_table('sequence', schema=None) as batch_op:
        # Step 3: Alter the column to be NOT NULL
        batch_op.alter_column('featured',
                           existing_type=sa.Integer(),
                           nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sequence', schema=None) as batch_op:
        batch_op.drop_column('featured')

    # ### end Alembic commands ###
