"""Add preview_temp_data table

Revision ID: 0eb3aba52b90
Revises: 411d6fb2b779
Create Date: 2026-04-04 22:56:20.718604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb3aba52b90'
down_revision = '411d6fb2b779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preview_temp_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('sequence_name', sa.String(length=100), nullable=True),
    sa.Column('timers_data', sa.Text(), nullable=True),
    sa.Column('loop_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('loop_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preview_temp_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preview_temp_data_session_id'), ['session_id'], unique=True)

    with op.batch_alter_table('sequence_share', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_verification_token', ['verification_token'])
        batch_op.create_unique_constraint('uq_user_reset_token', ['reset_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_verification_token', type_='unique')
        batch_op.drop_constraint('uq_user_reset_token', type_='unique')

    with op.batch_alter_table('sequence_share', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('preview_temp_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preview_temp_data_session_id'))

    op.drop_table('preview_temp_data')
    # ### end Alembic commands ###
