"""Add preview_token column to preview_temp_data

Revision ID: 132b3ae7ac6b
Revises: 0eb3aba52b90
Create Date: 2026-04-04 23:25:17.634494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132b3ae7ac6b'
down_revision = '0eb3aba52b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: This migration was manually applied due to SQLite limitations.
    # The preview_token column has been added and session_id made nullable.
    # This is a no-op for databases that already have the correct schema.
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preview_temp_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preview_temp_data_preview_token'))
        batch_op.drop_column('preview_token')
        batch_op.alter_column('session_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_preview_temp_data_session_id'), ['session_id'], unique=True)

    # ### end Alembic commands ###
