"""Add default column to Sound table and set 'Single Beep' as default

Revision ID: 3de499ca6634
Revises: 09ae21db0ff2
Create Date: 2025-06-04 20:27:45.079098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de499ca6634'
down_revision = '09ae21db0ff2'
branch_labels = None
depends_on = None


# Example: migrations/versions/xxxxxxxxxxxx_add_default_column_to_sound_table_and_set_single_beep_as_default.py
# ... (rest of the file content generated by alembic) ...

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sound', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###

    # --- MANUAL ADDITION START: Set 'Single Beep' as default ---
    # 1. Set all existing 'default' values to 0 (non-default)
    op.execute("UPDATE sound SET default = 0;")
    # 2. Then, set the 'default' column to 1 for the 'beep.mp3' sound
    op.execute("UPDATE sound SET default = 1 WHERE filename = 'beep.mp3';")
    # --- MANUAL ADDITION END ---

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sound', schema=None) as batch_op:
        batch_op.drop_column('default')
    # ### end Alembic commands ###