"""add user authentication system

Revision ID: a1b2c3d4e5f6
Revises: d35f9a43c70c
Create Date: 2025-03-30

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'd35f9a43c70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create user table
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False, default=False),
    sa.Column('verification_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('subscription_tier', sa.Enum('free', 'pro', 'team', name='subscriptiontier'), nullable=False, default='free'),
    sa.Column('subscription_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    
    # Create oauth_account table
    op.create_table('oauth_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=2048), nullable=True),
    sa.Column('refresh_token', sa.String(length=2048), nullable=True),
    sa.Column('token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='unique_provider_account')
    )
    op.create_index(op.f('ix_oauth_account_user_id'), 'oauth_account', ['user_id'], unique=False)
    
    # Create user_activity_log table
    op.create_table('user_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('sequence_id', sa.String(length=20), nullable=True),
    sa.Column('timer_order', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activity_log_user_id'), 'user_activity_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_activity_log_action'), 'user_activity_log', ['action'], unique=False)
    op.create_index(op.f('ix_user_activity_log_category'), 'user_activity_log', ['category'], unique=False)
    op.create_index(op.f('ix_user_activity_log_session_id'), 'user_activity_log', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_activity_log_sequence_id'), 'user_activity_log', ['sequence_id'], unique=False)
    op.create_index(op.f('ix_user_activity_log_timestamp'), 'user_activity_log', ['timestamp'], unique=False)
    
    # Add owner_id to sequence table
    with op.batch_alter_table('sequence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, default=True))
        batch_op.create_index(batch_op.f('ix_sequence_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key('fk_sequence_owner_id_user', 'user', ['owner_id'], ['id'])
    
    # Add owner_id to counter_log table
    with op.batch_alter_table('counter_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_counter_log_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key('fk_counter_log_owner_id_user', 'user', ['owner_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove owner_id from counter_log
    with op.batch_alter_table('counter_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_counter_log_owner_id_user', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_counter_log_owner_id'))
        batch_op.drop_column('owner_id')
    
    # Remove owner_id from sequence
    with op.batch_alter_table('sequence', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sequence_owner_id_user', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sequence_owner_id'))
        batch_op.drop_column('is_public')
        batch_op.drop_column('owner_id')
    
    # Drop tables
    op.drop_index(op.f('ix_user_activity_log_timestamp'), table_name='user_activity_log')
    op.drop_index(op.f('ix_user_activity_log_sequence_id'), table_name='user_activity_log')
    op.drop_index(op.f('ix_user_activity_log_session_id'), table_name='user_activity_log')
    op.drop_index(op.f('ix_user_activity_log_category'), table_name='user_activity_log')
    op.drop_index(op.f('ix_user_activity_log_action'), table_name='user_activity_log')
    op.drop_index(op.f('ix_user_activity_log_user_id'), table_name='user_activity_log')
    op.drop_table('user_activity_log')
    
    op.drop_index(op.f('ix_oauth_account_user_id'), table_name='oauth_account')
    op.drop_table('oauth_account')
    
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    
    # ### end Alembic commands ###
