"""Add indexes to performance critical columns

Revision ID: d35f9a43c70c
Revises: 8c2105aab655
Create Date: 2026-03-20 15:42:20.942707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35f9a43c70c'
down_revision = '8c2105aab655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counter_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counter_log_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_counter_log_sequence_id'), ['sequence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_counter_log_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('sequence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sequence_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sequence_featured'), ['featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_sequence_name'), ['name'], unique=False)

    with op.batch_alter_table('sound', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sound_default'), ['default'], unique=False)

    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timer_sequence_id'), ['sequence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timer_timer_order'), ['timer_order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timer_timer_order'))
        batch_op.drop_index(batch_op.f('ix_timer_sequence_id'))

    with op.batch_alter_table('sound', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sound_default'))

    with op.batch_alter_table('sequence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sequence_name'))
        batch_op.drop_index(batch_op.f('ix_sequence_featured'))
        batch_op.drop_index(batch_op.f('ix_sequence_created_at'))

    with op.batch_alter_table('counter_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counter_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_counter_log_sequence_id'))
        batch_op.drop_index(batch_op.f('ix_counter_log_event_type'))

    # ### end Alembic commands ###
