"""Add alarm_sound column to Timer table

Revision ID: f3c63690b200
Revises: 8d87172073d0
Create Date: 2025-05-26 23:40:17.725291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c63690b200'
down_revision = '8d87172073d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alarm_sound', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.drop_column('alarm_sound')

    # ### end Alembic commands ###
